#!/bin/bash
##################################################################################
# Description
##################################################################################
# This utility script is designed to force rocoto to run complex workflows that
# usuallly fail by default.  This was generated by testing and modifying the
# rocoto source such that the file
#
# rocoto/lib/workflowmgr/workflowengine.rb
# 
# line 408 is edited to read
#
# reply='y'
#
# thereby removing the interactive prompt.  This allows one to rocoto boot the
# next cycle first task by grepping the rocoto workflow logs and prompting the
# cycle to run when it will not trigger.  This is a very hacky solution and
# will be made obsolete when the system is fully re-written for using Cylc to
# improve performance, long-term support and overall reliability.
#
##################################################################################
# License Statement:
##################################################################################
# Copyright 2023 Colin Grudzien, cgrudzien@ucsd.edu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
##################################################################################

if [ ! ${CLNE_ROOT} ]; then 
  echo "ERROR: clone root \${CLNE_ROOT} is not defined."
  exit 1
fi

if [ ! ${CYC} ]; then
  echo "ERROR: next cycle date time \${CYC} is not defined."
  exit 1
fi

if [ ! ${CSE} ]; then
  echo "ERROR: case study \${CSE} is not defined."
  exit 1
fi

if [ ! ${FLW} ]; then
  echo "ERROR: control flow \${FLW} is not defined."
  exit 1
fi

# grep the next task from the workflow status log
IFS=" " read -ra cyc_stat <<< `grep "${CYC}" ${CLNE_ROOT}/workflow_status/${CSE}-${FLW}_workflow_status.txt | head -n 1`

# unpack next task to boot from the status log
tsk=${cyc_stat[1]}

cmd="cd ${CLNE_ROOT}"
echo ${cmd}; eval ${cmd}

cmd="python -c 'import rocoto_utilities; rocoto_utilities.run_rocotoboot([\"${CSE}\"],[\"${FLW}\"],[\"${CYC}\"],[\"${tsk}\"])'"
echo ${cmd}; eval ${cmd}

exit 0
